[package]
name = "djotfmt"
version = "0.1.0"
edition = "2021"

[patch.crates-io]
jotdown = { git = 'https://github.com/hellux/jotdown.git' }

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
colog = "1.3.0"
env_logger = "0.11.6"
jotdown = "0.7.0"
log = "0.4.27"
paste = "1.0.15"
pretty_assertions = "1.4.1"
roman = "0.1.6"
test_each_file = "0.3.4"
unicode-width = "0.2.0"
walkdir = "2.5.0"
