[package]
name = "djotfmt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
colog = "1.3.0"
env_logger = "0.11.5"
jotdown = "0.6.0"
log = "0.4.22"
walkdir = "2.5.0"
